apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
  labels:
    app: streamlit-app
spec:
  type: LoadBalancer  # For external access in Minikube; use NodePort for kind or internal access
  ports:
  - port: 80          # Port exposed by the service
    targetPort: 8501  # Port on which the container listens
    protocol: TCP
  selector:
    app: streamlit-app
